import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Banner from '../components/banner';
import Image from 'next/image';
import Card from '../components/card';
import { fetchCoffeeStores } from '../lib/coffee-stores';
import useTrackLocation from '../hooks/use-track-location';
import { useEffect, useState, useContext } from 'react';
import { ACTION_TYPES } from '../context/store-context';
import { StoreContext } from '../context/store-context';

// import coffeeStoresData from '../data/coffee-stores.json';

export async function getStaticProps(context) {

  const coffeeStores = await fetchCoffeeStores();

  return {
    props: {
      coffeeStores,
      city: coffeeStores[0].neighbourhood
    }
  }
}

export default function Home(props) {

  const { handleTrackLocation, locationErrorMsg, isFindingLoc } = useTrackLocation();

  // console.log({ latlong, locationErrorMsg });

  // const [coffeeStores, setCoffeeStores] = useState('');
  const [coffeeStoresError, setCoffeeStoresError] = useState(null);
  const { dispatch, state } = useContext(StoreContext);

  const { latlong, coffeeStores  } = state;

  useEffect(() => {
    async function fetchData() {
      if (latlong) {
        try {
          const res = await fetch(`/api/getCoffeeStoresByLocation?latlong=${latlong}&limit=5`);
          const fetchedCoffeeStores = await res.json();
          console.log("fetched coffee stores ", { fetchedCoffeeStores });
          // setCoffeeStores(fetchedCoffeeStores);
          dispatch({ type: ACTION_TYPES.SET_COFFEESTORES, payload: { coffeeStores: fetchedCoffeeStores } });
          //set coffee stores
          setCoffeeStoresError('');
        } catch (err) {
          //set error
          setCoffeeStoresError(err.message);
        }
      }

    }
    fetchData();}, [latlong])

  const handleOnBannerButtonClick = () => {
    console.log('clicked banner button');
    handleTrackLocation();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={isFindingLoc ? "Locating..." : "View stores nearby"}
          handleOnClick={handleOnBannerButtonClick} />
        {locationErrorMsg && <p>{locationErrorMsg }</p>}
        {coffeeStoresError && <p>{coffeeStoresError}</p>}
        <div className={styles.heroImage}>
          <Image src='/static/hero-image.png' width='700' height='400' />
        </div>

        {coffeeStores.length > 0 && <>
          <h2 className={styles.heading2}>{coffeeStores[0].neighbourhood} stores near me</h2>
          <div className={styles.cardLayout}>
            {coffeeStores.map(store => {
              return (
                <Card className={styles.card} key={store.id} name={store.name} imgUrl={store.imgUrl} href={`/coffee-store/${store.id}`} />
              )
            })}
          </div>
        </>}

        {props.coffeeStores.length > 0 && <>
          <h2 className={styles.heading2}>{props.city} stores</h2>
          <div className={styles.cardLayout}>
            {props.coffeeStores.map(store => {
              return (
                <Card className={styles.card} key={store.id} name={store.name} imgUrl={store.imgUrl} href={`/coffee-store/${store.id}`} />
              )
            })}
          </div>
        </>}

      </main>
    </div>
  )
}
